version: '3.6'
services:
 fastapi:
  build:
    context: ./dockerfiles
    dockerfile: Dockerfile-fastapi
  image: ${PROJECT}_fastapi
  volumes:
    - ${FOLDER-./project}:/app
  environment:
    - PHTONENV=/app
  ports:
    - ${FASTAPI_PORT-8000}:8000
  #command: uvicorn main:app --host 0.0.0.0 --reload
  networks:
    - dlaravel_net

networks:
    dlaravel_net:
