services:
 fastapi:
  build:
    context: ./dockerfiles
    dockerfile: Dockerfile-fastapi
  image: ${PROJECT}_fastapi
  volumes:
    - ${FOLDER-./project}:/app
  environment:
    - PHTONENV=/app
  ports:
    - ${FASTAPI_PORT-8000}:8000
  #command: bash -c ". /opt/python/bin/activate&&uvicorn --host 0.0.0.0 --app-dir /app main:app --reload"
  restart: unless-stopped
  networks:
    - dlaravel_net

networks:
    dlaravel_net:
