#!/bin/bash
if [ -f .env ];then
    source .env
    source .functions.sh
fi

if [[ "$1" = 'all' ]];then
    . ./all
    exit
fi

if [[ "$1" = 'ports' ]];then
    ./ports
    exit
fi

echo "DotEnv Settings"
if [ $DEFAULT ] && [ $DEFAULT = "random" ];then
    TERM_STDOUT=$(docker-compose -p ${PROJECT} ps)
    PORT=$(echo -e "$TERM_STDOUT"|grep "${PROJECT}-web-1"|sed -r 's/.+0.0.0.0:([[:digit:]]+)->80.+/\1/g')
    #cat .env|sed -r '/^#/d'|sed -r "s/^(APP_URL=.+):random/\1:${PORT}/g"
    if [ $PORT ];then
        cat .env|sed -r '/^#/d'|sed -r "s/^APP_URL=(.+):random/APP_URL=\1:${PORT}/g"
    else
        cat .env|sed -r '/^#/d'   
    fi
else
    cat .env|sed -r '/^#/d'   
fi
