#!/bin/bash
if [ -f .env ];then
    source .functions.sh
    #start multiple project
    if [[ "$1" = 'all' ]];then
            ./all start
        exit
    fi
    #single project
    PROJECT=$(grep 'PROJECT' .env|cut -d= -f2)
    start ${PROJECT}
else
    echo ".env not found"
fi
