#!/bin/bash
source .functions.sh
echo ${CURRENT_PROJECT_FILE}

for o in $(grep 'PROJECT' $(find envs -maxdepth 1 -type f -not -path 'envs/.*')|cut -d= -f2)
do
if [[ "envs/${o}" = ${CURRENT_PROJECT_FILE} ]]; then
    CURRENT="(* current link env.)"
    else
    CURRENT=""
fi
echo "Project: ${o} ${CURRENT}"
docker ps|grep ${o}_
echo ""
done
