#!/bin/bash
if [ -f .env ];then
    source .functions.sh
    #Stop multiple project
    if [[ "$1" = 'all' ]];then
            for PROJECT in $(grep 'PROJECT' $(find envs -type f -not -path 'envs/.*' -depth 1)|cut -d= -f2)
            do
                ENV_FILE=$(grep -lE "^PROJECT=${PROJECT}\$" envs/*)
                ln -sf ${ENV_FILE} .env
                source .env
                echo "Stop ${PROJECT}"
                stop ${PROJECT}
            done
            ./all
        exit
    fi
    #single project
    PROJECT=$(grep 'PROJECT' .env|cut -d= -f2)
    stop ${PROJECT}
else
    echo ".env not found"
fi
