#!/bin/bash
if [ -f .env ];then
    source .functions.sh
    #Stop multiple project
    if [[ "$1" = 'all' ]];then
            ./all stop
        exit
    fi
    #single project
    PROJECT=$(grep 'PROJECT' .env|cut -d= -f2)
    stop ${PROJECT}
else
    echo ".env not found"
fi
