#!/bin/bash
#Default SHELL
SHELL=bash
#Default workspace
WORKSPACE=php
#取得目前bash執行路徑
script_dir=$(dirname $0)
. ${script_dir}/.env
if [ $? -gt 0 ];then
    exit 1
fi

echo ${PROJECT}
export DOCKER_CLI_HINTS="false"

if [ $1 ];then
  WORKSPACE=$1
fi

docker exec -ti ${PROJECT}-${WORKSPACE}-1 ${SHELL}
