version: '3.7'
services:
 db:
  image: mariadb:10.5.5
  hostname: db
  volumes:
    - ./data/${PROJECT-default}:/var/lib/mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_ROOT_HOST=127.0.0.1
    - TZ=Asia/Taipei
  restart: unless-stopped
  networks:
    - dlaravel_net

networks:
    dlaravel_net:
