version: '3.6'
services:
 db:
  image: mariadb:10.5.5
  #ports:
  #  - ${DB_PORT-1250}:3306
  volumes:
    #- ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./data/${PROJECT-default}:/var/lib/mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
    - MYSQL_ROOT_HOST=127.0.0.1
    - TZ=Asia/Taipei
  restart: unless-stopped
  network_mode: service:ssh
