# redis ports
#- "127.0.0.1:6379:6379"

#Dockerhub官方redis image
version: '3.7'
services:
 redis:
  image: redis
  networks:
    - dlaravel_net
  command: redis-server --requirepass You_Should_Change_This_Password
  restart: unless-stopped
networks:
    dlaravel_net:
