From deviny/fpm:8.1.11-ssh
ARG USER_ID
ENV USER_ID ${USER_ID:-1000}

ARG GROUP_ID
ENV GROUP_ID ${GROUP_ID:-1000}

USER root
RUN sed -i "s/dlaravel:x:1000/dlaravel:x:${GROUP_ID}/" /etc/group
RUN usermod -u ${USER_ID} -g ${GROUP_ID} dlaravel
RUN chown -R ${USER_ID} /home/dlaravel
RUN chown ${USER_ID}:${GROUP_ID} /home/dlaravel -R
RUN chown ${USER_ID}:${GROUP_ID} /home/dlaravel/.ssh/authorized_keys
USER dlaravel
WORKDIR /var/www/html
