From deviny/fpm:8.3.4
ARG USER_ID
ENV USER_ID ${USER_ID:-1000}

ARG GROUP_ID
ENV GROUP_ID ${GROUP_ID:-1000}

USER root

RUN apt-get -y update
RUN apt-get install -y locales redis-tools openssh-server git pwgen
RUN mkdir -p /var/run/sshd /home/dlaravel/.ssh

RUN touch /home/dlaravel/.ssh/authorized_keys

RUN sed -i "s/dlaravel:x:1000/dlaravel:x:${GROUP_ID}/" /etc/group
RUN usermod -u ${USER_ID} -g ${GROUP_ID} dlaravel
RUN chown -R ${USER_ID} /home/dlaravel
RUN chown ${USER_ID}:${GROUP_ID} /home/dlaravel -R
RUN chown ${USER_ID}:${GROUP_ID} /home/dlaravel/.ssh/authorized_keys

COPY bash_aliases /home/dlaravel/.bash_aliases
RUN chown ${USER_ID}:${GROUP_ID} /home/dlaravel/.bash_aliases


RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
      sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
      sed -ri 's/#AuthorizedKeysFile/AuthorizedKeysFile/g' /etc/ssh/sshd_config && \
      sed -ri 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config

RUN echo "Asia/Taipei" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata && \
    sed -i -e 's/# zh_TW.UTF-8 UTF-8/zh_TW.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="zh_TW.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=zh_TW.UTF-8

RUN ssh-keygen -A

RUN echo "ExposeAuthInfo yes" >> /etc/ssh/sshd_config

#Download LTS VERSION
RUN export NODE_VERSION=$(curl -s https://nodejs.org/download/release/latest-v18.x/SHASUMS256.txt|grep linux-arm64.tar.xz|awk '{print $2}'|sed 's/-linux-arm64.tar.xz//g') && \
    wget https://nodejs.org/download/release/latest-v18.x/${NODE_VERSION}-linux-arm64.tar.xz && \
    tar -xJf ${NODE_VERSION}-linux-arm64.tar.xz && \
	rm ${NODE_VERSION}-linux-arm64.tar.xz && \
	mv ${NODE_VERSION}-linux-arm64 /usr/local/node && \
	echo 'export PATH=/usr/local/node/bin:$PATH' >> /etc/bash.bashrc && \
    export PATH=/usr/local/node/bin:$PATH && \
    npm install -g npm@latest

# Link /var/www/html to home director
RUN ln -s /var/www/html /home/dlaravel/html

# Add random password for dlaravel
RUN echo "dlaravel:`pwgen`" |chpasswd

USER dlaravel
ENV LANG zh_TW.UTF-8
ENV LANGUAGE zh_TW.UTF-8
ENV LC_ALL zh_TW.UTF-8
WORKDIR /var/www/html

CMD ["sudo","sh","-c","/usr/sbin/sshd -D&php-fpm"]
