FROM niruix/sshwifty:latest

ARG DEBIAN_FRONTEND=noninteractive

USER root


RUN apk update&&apk add bash openssh-client openssl

#ADD sshwifty.conf.json sshwifty.conf.json

ADD v3.ext /etc/ssl/v3.ext

USER sshwifty

RUN openssl req \
-new -newkey rsa:4096  \
-days 3650 -nodes -x509 -keyout /tmp/certkey -out /tmp/cert \
-config /etc/ssl/v3.ext -extensions 'v3_req'

#ENTRYPOINT ["/usr/bin/env"]

EXPOSE 8182 8183

ENV LANG zh_TW.UTF-8
ENV LANGUAGE zh_TW.UTF-8
ENV LC_ALL zh_TW.UTF-8

RUN ssh-keygen -f ${HOME}/.ssh/id_rsa -N '' -t rsa &&\  
    ssh-keygen -f ${HOME}/.ssh/id_dsa -N '' -t dsa &&\
    ssh-keygen -f ${HOME}/.ssh/id_ecdsa -N '' -t ecdsa &&\
    ssh-keygen -f ${HOME}/.ssh/id_ed25519 -N '' -t ed25519

CMD SSHWIFTY_CONFIG=./sshwifty.conf.json ./sshwifty
